version: '3.7'

services:
  app:
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
      args:
        DOCKER_GO_VERSION: $DOCKER_GO_VERSION
      labels:
        com.tg_saver.go.version: $DOCKER_GO_VERSION
    working_dir: /app
    volumes:
      - ..:/app
      - ../../go:/go
#      - ssh-data:/ssh:ro
    command: sh
    environment:
      - LINTER_TAG=$LINTER_TAG
      - DOCKER_GO_VERSION=$DOCKER_GO_VERSION

#volumes:
#  ssh-data:
#    external:
#      name: ssh_data
